insert into books (author, title, price_old, price) values ('Cindelyn Sammes', 'volutpat quam pede lobortis ligula', '$120.22', '$49.92');
insert into books (author, title, price_old, price) values ('Raynard Derby', 'suspendisse ornare consequat lectus', '$128.92', '$58.62');
insert into books (author, title, price_old, price) values ('Murry Lune', 'varius integer ac', '$197.62', '$72.22');
insert into books (author, title, price_old, price) values ('Thornie Flaxon', 'id luctus', '$176.92', '$10.92');
insert into books (author, title, price_old, price) values ('Winston Paule', 'dui vel', '$127.32', '$90.82');
insert into books (author, title, price_old, price) values ('Kristopher Atwood', 'lobortis ligula sit amet', '$108.32', '$12.62');
insert into books (author, title, price_old, price) values ('Tracey Blann', 'faucibus cursus urna ut tellus', '$124.72', '$23.12');
insert into books (author, title, price_old, price) values ('Colman Shadfourth', 'id consequat in consequat ut', '$174.42', '$11.92');
insert into books (author, title, price_old, price) values ('Murielle Pactat', 'nulla suspendisse potenti', '$102.62', '$41.62');
insert into books (author, title, price_old, price) values ('Templeton Duhig', 'neque aenean auctor', '$125.42', '$66.62');
insert into books (author, title, price_old, price) values ('Kandy Lowne', 'turpis a pede posuere', '$165.42', '$96.72');
insert into books (author, title, price_old, price) values ('Cheryl Pember', 'eu nibh quisque', '$111.72', '$85.92');
insert into books (author, title, price_old, price) values ('Mal Gilmore', 'ultrices posuere cubilia', '$131.82', '$41.32');
insert into books (author, title, price_old, price) values ('Kelley Smallpiece', 'sapien urna', '$155.02', '$56.22');
insert into books (author, title, price_old, price) values ('Olivia Carleman', 'aliquam erat volutpat in', '$176.82', '$83.12');
insert into books (author, title, price_old, price) values ('Linnie Bothen', 'quis lectus suspendisse', '$151.02', '$59.82');
insert into books (author, title, price_old, price) values ('Nicholas Korda', 'nunc proin at', '$181.42', '$91.32');
insert into books (author, title, price_old, price) values ('Port Barkas', 'adipiscing lorem vitae', '$118.42', '$13.82');
insert into books (author, title, price_old, price) values ('Paulina Haton', 'libero non', '$189.72', '$23.12');
insert into books (author, title, price_old, price) values ('Orbadiah Feathers', 'lorem ipsum dolor sit', '$180.62', '$68.72');
insert into books (author, title, price_old, price) values ('Spenser Jacomb', 'donec ut mauris eget massa', '$103.92', '$56.82');
insert into books (author, title, price_old, price) values ('Johnette de Chastelain', 'ridiculus mus etiam vel augue', '$143.92', '$36.82');
insert into books (author, title, price_old, price) values ('Noel Keveren', 'fermentum justo nec condimentum neque', '$177.72', '$30.92');
insert into books (author, title, price_old, price) values ('Nathalie Salla', 'sed tincidunt eu felis fusce', '$199.12', '$68.42');
insert into books (author, title, price_old, price) values ('Prent Helwig', 'nam tristique tortor eu', '$164.52', '$59.12');
insert into books (author, title, price_old, price) values ('Deny Loadsman', 'ipsum primis in faucibus orci', '$179.02', '$04.92');
insert into books (author, title, price_old, price) values ('Mozes Lyffe', 'phasellus in felis donec', '$155.62', '$32.82');
insert into books (author, title, price_old, price) values ('Colline Greatbach', 'leo maecenas pulvinar lobortis est', '$185.92', '$93.82');
insert into books (author, title, price_old, price) values ('Kaleena Bineham', 'interdum venenatis turpis enim blandit', '$163.02', '$75.02');
insert into books (author, title, price_old, price) values ('Erie Wurz', 'nam dui proin leo', '$177.22', '$20.62');
insert into books (author, title, price_old, price) values ('Kenton Westwell', 'vel accumsan tellus nisi', '$140.72', '$45.22');
insert into books (author, title, price_old, price) values ('Karia Jirus', 'suscipit nulla elit', '$170.82', '$55.92');
insert into books (author, title, price_old, price) values ('Kalli Galier', 'nunc commodo placerat praesent', '$179.72', '$89.22');
insert into books (author, title, price_old, price) values ('Helge Ianiello', 'vitae consectetuer eget rutrum at', '$174.12', '$28.12');
insert into books (author, title, price_old, price) values ('Brendis Sellwood', 'nulla suspendisse', '$148.02', '$92.52');
insert into books (author, title, price_old, price) values ('Stanford Marsden', 'ornare imperdiet sapien urna pretium', '$192.52', '$66.02');
insert into books (author, title, price_old, price) values ('Michaella Oswald', 'justo lacinia', '$186.12', '$97.62');
insert into books (author, title, price_old, price) values ('Nissa Jullian', 'pellentesque volutpat dui maecenas', '$105.32', '$02.42');
insert into books (author, title, price_old, price) values ('Gareth Lackmann', 'et magnis dis', '$187.92', '$89.12');
insert into books (author, title, price_old, price) values ('Rachel Bottini', 'suspendisse potenti', '$125.82', '$86.72');
insert into books (author, title, price_old, price) values ('Gary Batistelli', 'vitae mattis nibh ligula', '$195.72', '$14.02');
insert into books (author, title, price_old, price) values ('Jerri Payne', 'nunc vestibulum ante', '$167.22', '$09.12');
insert into books (author, title, price_old, price) values ('Gregor Carlino', 'ante nulla justo', '$196.52', '$29.02');
insert into books (author, title, price_old, price) values ('Eloise Concannon', 'at nulla suspendisse potenti', '$140.72', '$99.12');
insert into books (author, title, price_old, price) values ('Trace Woolis', 'dui luctus rutrum nulla tellus', '$189.12', '$29.82');
insert into books (author, title, price_old, price) values ('Zachary Dewfall', 'ultrices enim lorem', '$148.62', '$93.92');
insert into books (author, title, price_old, price) values ('Alvera Rizzardini', 'interdum in ante vestibulum ante', '$184.62', '$29.12');
insert into books (author, title, price_old, price) values ('Clarey Reicharz', 'a nibh', '$116.32', '$22.02');
insert into books (author, title, price_old, price) values ('Ely Vasilkov', 'ipsum praesent blandit', '$119.52', '$81.12');
insert into books (author, title, price_old, price) values ('Base Rubinowitch', 'tincidunt eget tempus vel pede', '$161.92', '$76.12');
insert into books (author, title, price_old, price) values ('Beverlee Ownsworth', 'blandit nam nulla', '$101.82', '$13.12');
insert into books (author, title, price_old, price) values ('Tallie Ayris', 'arcu libero rutrum', '$118.42', '$12.72');
insert into books (author, title, price_old, price) values ('Jacquelynn McDonald', 'felis sed', '$113.62', '$81.62');
insert into books (author, title, price_old, price) values ('Annissa Rose', 'lacinia nisi', '$160.72', '$21.72');
insert into books (author, title, price_old, price) values ('Maisey Hamman', 'adipiscing lorem', '$118.82', '$87.22');
insert into books (author, title, price_old, price) values ('Grenville Krolman', 'nisi volutpat eleifend donec', '$115.82', '$98.42');
insert into books (author, title, price_old, price) values ('Lowell Sutch', 'nisl aenean lectus pellentesque eget', '$178.82', '$77.82');
insert into books (author, title, price_old, price) values ('Verina Matushenko', 'suspendisse accumsan tortor', '$118.92', '$44.92');
insert into books (author, title, price_old, price) values ('Dudley Clery', 'hac habitasse platea dictumst', '$138.02', '$73.02');
insert into books (author, title, price_old, price) values ('Gusti Filipson', 'quis turpis eget elit', '$180.32', '$41.42');
insert into books (author, title, price_old, price) values ('Kenny Devaney', 'congue risus semper porta volutpat', '$152.02', '$35.92');
insert into books (author, title, price_old, price) values ('Paco Mulderrig', 'a nibh', '$187.62', '$65.52');
insert into books (author, title, price_old, price) values ('Brunhilde Buttle', 'varius integer ac leo pellentesque', '$192.72', '$47.32');
insert into books (author, title, price_old, price) values ('Corrina Mechell', 'ut odio', '$145.22', '$19.32');
insert into books (author, title, price_old, price) values ('Boigie Henlon', 'eu orci mauris lacinia', '$155.42', '$47.62');
insert into books (author, title, price_old, price) values ('Lurette Eastby', 'platea dictumst', '$164.52', '$93.92');
insert into books (author, title, price_old, price) values ('Randene Rudolfer', 'in congue', '$103.42', '$78.42');
insert into books (author, title, price_old, price) values ('Kaiser Geistbeck', 'libero nullam sit', '$109.92', '$23.62');
insert into books (author, title, price_old, price) values ('Bren Winspur', 'pede venenatis non', '$115.92', '$47.72');
insert into books (author, title, price_old, price) values ('Shanon Liddiatt', 'ut massa volutpat', '$136.32', '$44.82');
insert into books (author, title, price_old, price) values ('Lawton Dominy', 'aliquam erat', '$111.82', '$13.82');
insert into books (author, title, price_old, price) values ('Mattheus Rugg', 'dui vel', '$104.32', '$78.92');
insert into books (author, title, price_old, price) values ('Johnna Kliemchen', 'vestibulum velit id pretium iaculis', '$109.72', '$95.42');
insert into books (author, title, price_old, price) values ('Lyndsie Brandin', 'sit amet sapien dignissim', '$143.82', '$39.42');
insert into books (author, title, price_old, price) values ('Cecile Astles', 'nisi at nibh in hac', '$182.42', '$19.72');
insert into books (author, title, price_old, price) values ('Winfield Goudy', 'posuere cubilia', '$136.02', '$69.72');
insert into books (author, title, price_old, price) values ('Mozes Pursehouse', 'amet eleifend pede libero quis', '$134.02', '$13.92');
insert into books (author, title, price_old, price) values ('Frayda MacGray', 'leo maecenas pulvinar lobortis est', '$133.92', '$96.02');
insert into books (author, title, price_old, price) values ('Keriann Bresner', 'ultrices posuere cubilia curae nulla', '$101.22', '$73.82');
insert into books (author, title, price_old, price) values ('Siusan Kliesl', 'morbi non quam nec dui', '$177.12', '$22.12');
insert into books (author, title, price_old, price) values ('Dulcine Stollberger', 'luctus nec', '$153.22', '$22.72');
insert into books (author, title, price_old, price) values ('Stephi Roddam', 'vestibulum ac', '$167.42', '$03.72');
insert into books (author, title, price_old, price) values ('Selene Fomichkin', 'venenatis non sodales', '$194.92', '$65.62');
insert into books (author, title, price_old, price) values ('Maggi Bielfeldt', 'eget massa tempor', '$133.72', '$35.02');
insert into books (author, title, price_old, price) values ('Ines Wilflinger', 'ut massa volutpat convallis', '$113.72', '$69.52');
insert into books (author, title, price_old, price) values ('Debi O''Malley', 'ultrices posuere cubilia curae', '$165.02', '$20.32');
insert into books (author, title, price_old, price) values ('Spence Beaze', 'volutpat quam pede lobortis', '$190.52', '$73.72');
insert into books (author, title, price_old, price) values ('Robers Uman', 'molestie nibh in lectus', '$168.22', '$81.92');
insert into books (author, title, price_old, price) values ('Reed McAllister', 'bibendum imperdiet nullam orci pede', '$157.52', '$68.72');
insert into books (author, title, price_old, price) values ('Malia Muino', 'cubilia curae mauris viverra diam', '$195.62', '$45.92');
insert into books (author, title, price_old, price) values ('Toiboid Rimes', 'sed nisl nunc rhoncus dui', '$171.92', '$77.22');
insert into books (author, title, price_old, price) values ('Daryn Hanbridge', 'pede morbi porttitor lorem', '$123.22', '$18.12');
insert into books (author, title, price_old, price) values ('Chrissie Ander', 'pede malesuada in', '$139.42', '$57.72');
insert into books (author, title, price_old, price) values ('Ugo Caldroni', 'ipsum dolor sit amet', '$146.02', '$81.42');
insert into books (author, title, price_old, price) values ('Emmalee Padbury', 'duis faucibus accumsan odio curabitur', '$189.92', '$05.82');
insert into books (author, title, price_old, price) values ('Sunshine Spyby', 'aenean auctor gravida', '$122.42', '$28.22');
insert into books (author, title, price_old, price) values ('Ester Bridden', 'nibh in quis justo maecenas', '$170.02', '$62.32');
insert into books (author, title, price_old, price) values ('Billy Gilffillan', 'maecenas pulvinar lobortis est phasellus', '$149.32', '$67.32');
insert into books (author, title, price_old, price) values ('Quill Stilling', 'dui vel sem sed sagittis', '$158.72', '$03.32');
insert into books (author, title, price_old, price) values ('Robinet Dudmesh', 'ut at dolor quis', '$138.32', '$23.52');
insert into books (author, title, price_old, price) values ('Brigida Eadington', 'vestibulum sed magna at nunc', '$158.72', '$97.02');
insert into books (author, title, price_old, price) values ('Rena Culy', 'in ante vestibulum', '$170.72', '$01.32');
insert into books (author, title, price_old, price) values ('Whitman Patrie', 'justo sollicitudin ut', '$187.62', '$10.12');
insert into books (author, title, price_old, price) values ('Jehanna Urrey', 'luctus nec molestie sed justo', '$140.82', '$09.82');
insert into books (author, title, price_old, price) values ('Gabbie Kell', 'dolor sit amet consectetuer', '$114.82', '$45.02');
insert into books (author, title, price_old, price) values ('Andie Weale', 'aliquet pulvinar sed', '$180.42', '$77.72');
insert into books (author, title, price_old, price) values ('Carmelia Eannetta', 'at turpis a pede posuere', '$163.82', '$06.92');
insert into books (author, title, price_old, price) values ('Charles Jales', 'ridiculus mus vivamus vestibulum', '$173.02', '$81.72');
insert into books (author, title, price_old, price) values ('Euell Bruggeman', 'dis parturient montes', '$142.92', '$51.92');
insert into books (author, title, price_old, price) values ('Kalle Careswell', 'vulputate ut ultrices', '$170.42', '$34.52');
insert into books (author, title, price_old, price) values ('Zerk Eccott', 'morbi quis tortor id', '$149.72', '$96.12');
insert into books (author, title, price_old, price) values ('Francine Garrique', 'metus aenean fermentum donec', '$199.02', '$66.72');
insert into books (author, title, price_old, price) values ('Lauryn Clearie', 'quam a odio in', '$125.72', '$31.22');
insert into books (author, title, price_old, price) values ('Juline Danit', 'dolor vel est', '$104.02', '$03.42');
insert into books (author, title, price_old, price) values ('Emlyn Dayly', 'congue elementum in', '$172.62', '$37.62');
insert into books (author, title, price_old, price) values ('Mattias Aldgate', 'tristique in tempus sit', '$172.12', '$19.32');
insert into books (author, title, price_old, price) values ('Oralia Hull', 'in ante vestibulum', '$105.32', '$26.62');
insert into books (author, title, price_old, price) values ('Lucila Frazier', 'non sodales', '$132.62', '$57.62');
insert into books (author, title, price_old, price) values ('Lisbeth O''Haire', 'tincidunt nulla', '$183.92', '$65.42');
insert into books (author, title, price_old, price) values ('Duke Andrelli', 'sapien iaculis congue', '$142.82', '$44.12');
insert into books (author, title, price_old, price) values ('Arda Bottrell', 'dui proin leo odio porttitor', '$110.02', '$86.42');
insert into books (author, title, price_old, price) values ('Tristam Whitewood', 'lacinia erat vestibulum', '$198.12', '$84.02');
insert into books (author, title, price_old, price) values ('Veradis Bortolazzi', 'dapibus at diam', '$116.42', '$42.52');
insert into books (author, title, price_old, price) values ('Wainwright Fenton', 'dui vel nisl duis', '$110.52', '$33.82');
insert into books (author, title, price_old, price) values ('Rance Aucock', 'massa volutpat convallis morbi odio', '$174.92', '$97.42');
insert into books (author, title, price_old, price) values ('Alister Fridlington', 'cras in purus eu magna', '$110.72', '$68.02');
insert into books (author, title, price_old, price) values ('Ginelle Frissell', 'nulla ut erat id', '$192.02', '$36.12');
insert into books (author, title, price_old, price) values ('Gwynne Arundel', 'vitae nisl aenean lectus', '$182.22', '$07.72');
insert into books (author, title, price_old, price) values ('Sheila Billie', 'molestie hendrerit at', '$125.12', '$46.02');
insert into books (author, title, price_old, price) values ('Mozelle Toghill', 'nisl venenatis', '$156.72', '$34.12');
insert into books (author, title, price_old, price) values ('Gwennie Kalinsky', 'ac diam cras', '$161.82', '$89.12');
insert into books (author, title, price_old, price) values ('Annetta Lacknor', 'maecenas pulvinar lobortis est phasellus', '$107.32', '$20.92');
insert into books (author, title, price_old, price) values ('Kristy Stollenberg', 'suspendisse potenti in eleifend', '$121.52', '$25.92');
insert into books (author, title, price_old, price) values ('Danila Reubens', 'eu mi', '$184.62', '$99.42');
insert into books (author, title, price_old, price) values ('Jourdain Orhrt', 'magna ac consequat metus sapien', '$129.62', '$28.72');
insert into books (author, title, price_old, price) values ('Caye Tomalin', 'sit amet lobortis sapien', '$157.42', '$58.32');
insert into books (author, title, price_old, price) values ('Paulita Mattiussi', 'commodo vulputate justo in', '$172.82', '$49.82');
insert into books (author, title, price_old, price) values ('Alfy Gethin', 'curabitur gravida nisi', '$158.32', '$47.82');
insert into books (author, title, price_old, price) values ('Loreen Harby', 'mauris sit amet eros suspendisse', '$149.02', '$65.32');
insert into books (author, title, price_old, price) values ('Rurik O''Doghesty', 'vulputate luctus', '$172.02', '$94.12');
insert into books (author, title, price_old, price) values ('Letta Horley', 'et eros vestibulum ac', '$147.52', '$50.02');
insert into books (author, title, price_old, price) values ('Helli Luc', 'euismod scelerisque quam turpis', '$184.32', '$91.52');
insert into books (author, title, price_old, price) values ('Ginni Halt', 'sem praesent id massa id', '$104.12', '$56.82');
insert into books (author, title, price_old, price) values ('Garnet Russ', 'massa id', '$101.62', '$45.02');
insert into books (author, title, price_old, price) values ('Sue Melsome', 'venenatis turpis enim blandit mi', '$101.72', '$90.12');
insert into books (author, title, price_old, price) values ('Lanette Ducker', 'nulla eget eros elementum', '$125.82', '$34.42');
insert into books (author, title, price_old, price) values ('Gearard Lidstone', 'sem fusce consequat nulla nisl', '$109.62', '$16.12');
insert into books (author, title, price_old, price) values ('Al Kirman', 'id ligula suspendisse', '$177.62', '$25.12');
insert into books (author, title, price_old, price) values ('Kinnie Scurrell', 'vel nulla eget', '$100.92', '$20.22');
insert into books (author, title, price_old, price) values ('Meara Russe', 'nunc proin at', '$132.52', '$39.02');
insert into books (author, title, price_old, price) values ('Wesley McLuckie', 'fermentum justo nec condimentum', '$182.42', '$67.72');
insert into books (author, title, price_old, price) values ('Erhart Fallis', 'adipiscing molestie hendrerit', '$137.42', '$30.92');
insert into books (author, title, price_old, price) values ('Pascal Hanham', 'at lorem integer tincidunt ante', '$164.72', '$21.22');
insert into books (author, title, price_old, price) values ('Calli De Robertis', 'lectus pellentesque eget nunc', '$119.92', '$34.82');
insert into books (author, title, price_old, price) values ('Wilek Leggon', 'pede ullamcorper', '$190.62', '$11.12');
insert into books (author, title, price_old, price) values ('Evania Mcasparan', 'nulla tellus in sagittis dui', '$104.22', '$08.32');
insert into books (author, title, price_old, price) values ('Adelheid Napoleon', 'consequat lectus in est', '$103.92', '$30.32');
insert into books (author, title, price_old, price) values ('Hannie Adkin', 'aliquam erat', '$146.52', '$13.82');
insert into books (author, title, price_old, price) values ('Nannette O'' Markey', 'volutpat eleifend donec ut', '$177.02', '$29.72');
insert into books (author, title, price_old, price) values ('Pinchas Ivanchin', 'sociis natoque', '$100.82', '$30.52');
insert into books (author, title, price_old, price) values ('Katusha Mossop', 'sit amet lobortis sapien', '$144.82', '$64.92');
insert into books (author, title, price_old, price) values ('Mitch Ferentz', 'nulla facilisi cras non', '$169.92', '$84.12');
insert into books (author, title, price_old, price) values ('Sonny Pawlyn', 'integer ac leo', '$103.62', '$18.02');
insert into books (author, title, price_old, price) values ('Shelden Humbey', 'sit amet cursus id', '$127.32', '$33.32');
insert into books (author, title, price_old, price) values ('Boyce Wichard', 'dapibus dolor vel est', '$163.72', '$74.12');
insert into books (author, title, price_old, price) values ('Corabelle Raggatt', 'sed accumsan felis', '$175.42', '$56.22');
insert into books (author, title, price_old, price) values ('Jessee Khalid', 'est et tempus semper est', '$191.32', '$89.32');
insert into books (author, title, price_old, price) values ('Pattie Goulter', 'phasellus sit amet', '$195.92', '$28.92');
insert into books (author, title, price_old, price) values ('Danni Doiley', 'amet nulla quisque', '$104.82', '$01.02');
insert into books (author, title, price_old, price) values ('John Foat', 'odio porttitor id consequat', '$135.62', '$82.92');
insert into books (author, title, price_old, price) values ('Nedda Cicutto', 'pellentesque ultrices mattis odio donec', '$198.52', '$43.42');
insert into books (author, title, price_old, price) values ('Kariotta Langdridge', 'habitasse platea', '$146.62', '$97.72');
insert into books (author, title, price_old, price) values ('Stafford Potbury', 'felis sed interdum venenatis turpis', '$129.82', '$74.82');
insert into books (author, title, price_old, price) values ('Levy Woodworth', 'tincidunt nulla mollis', '$173.12', '$06.32');
insert into books (author, title, price_old, price) values ('Corbie Brugger', 'scelerisque mauris sit amet', '$189.52', '$45.22');
insert into books (author, title, price_old, price) values ('Chrisse Scotts', 'diam nam', '$173.42', '$47.12');
insert into books (author, title, price_old, price) values ('Shelby Minors', 'ac diam cras pellentesque volutpat', '$128.92', '$71.82');
insert into books (author, title, price_old, price) values ('Del Butlin', 'volutpat convallis morbi', '$154.62', '$97.12');
insert into books (author, title, price_old, price) values ('Korrie Dows', 'rhoncus mauris enim leo', '$130.62', '$62.32');
insert into books (author, title, price_old, price) values ('Gardy Bantham', 'consequat dui nec nisi', '$112.52', '$66.12');
insert into books (author, title, price_old, price) values ('Faulkner Carbry', 'vulputate nonummy maecenas tincidunt lacus', '$104.32', '$16.12');
insert into books (author, title, price_old, price) values ('Cassius Hundall', 'orci luctus et ultrices', '$102.82', '$83.52');
insert into books (author, title, price_old, price) values ('Rachele Parkey', 'mauris enim leo', '$160.72', '$94.02');
insert into books (author, title, price_old, price) values ('Britte Keynd', 'maecenas pulvinar lobortis', '$133.42', '$68.12');
insert into books (author, title, price_old, price) values ('Ewell Grocutt', 'nunc viverra dapibus nulla suscipit', '$191.32', '$59.32');
insert into books (author, title, price_old, price) values ('Bennie Aggus', 'lacus morbi sem mauris', '$120.92', '$07.82');
insert into books (author, title, price_old, price) values ('Adele Gammett', 'odio porttitor id', '$178.52', '$73.42');
insert into books (author, title, price_old, price) values ('D''arcy Garnam', 'potenti in eleifend', '$122.42', '$91.82');
insert into books (author, title, price_old, price) values ('Belita Veryard', 'orci eget orci vehicula', '$162.12', '$06.22');
insert into books (author, title, price_old, price) values ('Cecily Sarson', 'posuere cubilia curae duis faucibus', '$122.62', '$61.72');
insert into books (author, title, price_old, price) values ('Nat McGreal', 'ante nulla justo aliquam', '$196.72', '$56.32');
insert into books (author, title, price_old, price) values ('Thomasina D''Enrico', 'nulla suscipit ligula in lacus', '$118.72', '$07.12');
insert into books (author, title, price_old, price) values ('Loni Filyashin', 'dis parturient montes nascetur ridiculus', '$189.82', '$12.12');
insert into books (author, title, price_old, price) values ('Friedrich Fautley', 'tellus nisi eu orci mauris', '$171.32', '$41.32');
insert into books (author, title, price_old, price) values ('Austin Sealey', 'diam id ornare imperdiet sapien', '$122.52', '$29.02');
insert into books (author, title, price_old, price) values ('Cairistiona McMurray', 'in lacus curabitur', '$186.12', '$33.52');
insert into books (author, title, price_old, price) values ('Delmar MacAne', 'vel augue vestibulum', '$156.42', '$22.32');
insert into books (author, title, price_old, price) values ('Elyn French', 'praesent lectus vestibulum', '$123.42', '$77.82');
insert into books (author, title, price_old, price) values ('Pat Sherrett', 'non velit nec nisi', '$131.82', '$95.52');
insert into books (author, title, price_old, price) values ('Tamarah Fardy', 'in lacus curabitur at', '$196.02', '$66.32');
insert into books (author, title, price_old, price) values ('Karol Saffill', 'consequat morbi', '$100.42', '$62.52');
insert into books (author, title, price_old, price) values ('Benoit Kamien', 'in faucibus orci', '$133.32', '$62.92');
insert into books (author, title, price_old, price) values ('Donalt Dumper', 'mi sit amet lobortis sapien', '$124.42', '$52.52');
insert into books (author, title, price_old, price) values ('Matthaeus Shipsey', 'ac neque duis bibendum morbi', '$104.82', '$95.32');
insert into books (author, title, price_old, price) values ('Pattie Rosiello', 'sapien iaculis congue vivamus metus', '$189.72', '$39.22');
insert into books (author, title, price_old, price) values ('Nevsa Vasilik', 'massa id lobortis convallis', '$134.42', '$38.22');
insert into books (author, title, price_old, price) values ('Tabatha Chowne', 'vulputate luctus', '$103.42', '$69.12');
insert into books (author, title, price_old, price) values ('Roselle Esposita', 'viverra eget congue eget', '$109.72', '$59.52');
insert into books (author, title, price_old, price) values ('Franciskus McNaught', 'ac leo pellentesque ultrices mattis', '$193.32', '$62.62');
insert into books (author, title, price_old, price) values ('Midge Hasley', 'praesent blandit', '$197.72', '$51.42');
insert into books (author, title, price_old, price) values ('Lani Cicutto', 'vivamus vestibulum', '$105.22', '$05.02');
insert into books (author, title, price_old, price) values ('Candie Chaff', 'purus aliquet', '$151.62', '$05.42');
insert into books (author, title, price_old, price) values ('Brendon Rye', 'turpis donec posuere', '$199.02', '$54.32');
insert into books (author, title, price_old, price) values ('Diann Vanyashkin', 'rutrum nulla tellus', '$140.22', '$18.92');
insert into books (author, title, price_old, price) values ('Lanae Dever', 'donec pharetra', '$104.12', '$86.32');
insert into books (author, title, price_old, price) values ('Peggie Kyneton', 'mauris ullamcorper', '$198.52', '$83.22');
insert into books (author, title, price_old, price) values ('Joyce Lorkings', 'posuere felis', '$145.12', '$52.22');
insert into books (author, title, price_old, price) values ('Lesli Shawl', 'risus dapibus augue vel accumsan', '$142.62', '$39.22');
insert into books (author, title, price_old, price) values ('Stafford Craigmyle', 'suscipit a', '$185.62', '$50.22');
insert into books (author, title, price_old, price) values ('Maddie Glenfield', 'sem praesent id massa', '$189.62', '$38.12');
insert into books (author, title, price_old, price) values ('Greggory Darwin', 'vitae nisl aenean', '$171.12', '$75.62');
insert into books (author, title, price_old, price) values ('Debera Brasher', 'nulla nunc', '$155.52', '$59.92');
insert into books (author, title, price_old, price) values ('Bell Nelissen', 'a libero nam', '$183.72', '$65.62');
insert into books (author, title, price_old, price) values ('Ermin Parsonson', 'natoque penatibus', '$122.52', '$63.92');
insert into books (author, title, price_old, price) values ('Mozes But', 'curabitur at', '$172.32', '$86.12');
insert into books (author, title, price_old, price) values ('Clare Fahrenbacher', 'augue luctus tincidunt nulla mollis', '$161.62', '$51.82');
insert into books (author, title, price_old, price) values ('Diena Boorer', 'nam congue risus', '$133.42', '$04.32');
insert into books (author, title, price_old, price) values ('Benjamin Beamand', 'massa volutpat convallis morbi odio', '$189.32', '$52.22');
insert into books (author, title, price_old, price) values ('Iolanthe Farress', 'a feugiat et eros vestibulum', '$157.92', '$53.52');
insert into books (author, title, price_old, price) values ('Cordie Monget', 'aliquam sit amet diam', '$160.72', '$41.02');
insert into books (author, title, price_old, price) values ('Myrwyn Arrault', 'eu interdum eu tincidunt', '$154.12', '$32.42');
insert into books (author, title, price_old, price) values ('Maggee Rittmeyer', 'ante vel ipsum', '$169.82', '$72.32');
insert into books (author, title, price_old, price) values ('Hedda Mccaull', 'vivamus in felis', '$113.82', '$85.32');
insert into books (author, title, price_old, price) values ('Granthem Snowsill', 'parturient montes nascetur ridiculus', '$125.22', '$01.02');
insert into books (author, title, price_old, price) values ('Dur Grisbrook', 'pretium quis lectus suspendisse', '$172.02', '$83.22');
insert into books (author, title, price_old, price) values ('Annie Scanlon', 'dui nec nisi volutpat eleifend', '$116.22', '$12.42');
insert into books (author, title, price_old, price) values ('Maighdiln Witchell', 'aliquam augue quam sollicitudin vitae', '$143.52', '$89.92');
insert into books (author, title, price_old, price) values ('Reagen Parley', 'lacinia sapien quis libero nullam', '$102.52', '$90.32');
insert into books (author, title, price_old, price) values ('Gilles Stempe', 'ut rhoncus aliquet pulvinar', '$196.12', '$26.42');
insert into books (author, title, price_old, price) values ('Eric Ervine', 'felis ut at', '$132.82', '$93.92');
insert into books (author, title, price_old, price) values ('Rosamund Cohane', 'neque vestibulum eget', '$137.62', '$63.52');
insert into books (author, title, price_old, price) values ('Cletis Aslam', 'duis bibendum', '$192.12', '$89.12');
insert into books (author, title, price_old, price) values ('Donia Dumberrill', 'ultrices enim', '$145.52', '$94.22');
insert into books (author, title, price_old, price) values ('Kamillah Giff', 'aliquet ultrices erat', '$127.52', '$76.92');
insert into books (author, title, price_old, price) values ('Ingemar Johnston', 'in est risus auctor', '$130.92', '$60.32');
insert into books (author, title, price_old, price) values ('Silvain Ever', 'eget massa tempor', '$103.72', '$87.22');
insert into books (author, title, price_old, price) values ('Ethelind Rochewell', 'donec posuere metus vitae ipsum', '$190.72', '$37.62');
insert into books (author, title, price_old, price) values ('Faustina Cisson', 'sapien iaculis congue', '$164.92', '$75.92');
insert into books (author, title, price_old, price) values ('Melicent Hamper', 'varius ut blandit', '$145.72', '$11.52');
insert into books (author, title, price_old, price) values ('Koenraad Beddingham', 'augue vestibulum', '$175.72', '$07.82');
insert into books (author, title, price_old, price) values ('Ruprecht Ockleshaw', 'magna vulputate luctus', '$111.42', '$26.22');
insert into books (author, title, price_old, price) values ('Murial Bucke', 'phasellus sit amet erat', '$141.22', '$61.52');
insert into books (author, title, price_old, price) values ('Dennis Legister', 'sagittis dui vel nisl', '$178.22', '$09.32');
insert into books (author, title, price_old, price) values ('Tomas Prosh', 'sit amet', '$102.02', '$85.92');
insert into books (author, title, price_old, price) values ('Danika Staddart', 'mauris non', '$132.22', '$06.02');
insert into books (author, title, price_old, price) values ('Michael Basill', 'ultrices posuere', '$182.22', '$49.02');
insert into books (author, title, price_old, price) values ('Felicle Joslin', 'amet cursus', '$180.42', '$84.42');
insert into books (author, title, price_old, price) values ('Rakel Doogan', 'luctus rutrum nulla tellus', '$171.92', '$50.02');
insert into books (author, title, price_old, price) values ('Farah Gillbee', 'vestibulum aliquet ultrices erat tortor', '$107.02', '$38.22');
insert into books (author, title, price_old, price) values ('Peyton Wellesley', 'bibendum imperdiet', '$184.52', '$67.62');
insert into books (author, title, price_old, price) values ('Mina Rama', 'adipiscing lorem vitae', '$173.52', '$79.72');
insert into books (author, title, price_old, price) values ('Marta Aguilar', 'sociis natoque penatibus', '$173.62', '$63.62');
insert into books (author, title, price_old, price) values ('Meryl Cramer', 'blandit non interdum', '$140.82', '$50.72');
insert into books (author, title, price_old, price) values ('Cherise Fremantle', 'non ligula pellentesque ultrices', '$191.82', '$40.72');
insert into books (author, title, price_old, price) values ('Claire Jowers', 'velit eu est congue', '$194.52', '$54.12');
insert into books (author, title, price_old, price) values ('Laurena Eborall', 'quis justo maecenas rhoncus aliquam', '$170.62', '$99.12');
insert into books (author, title, price_old, price) values ('Theda Degoy', 'pellentesque ultrices', '$173.32', '$44.02');
insert into books (author, title, price_old, price) values ('Tanny Haskey', 'nullam sit amet turpis', '$140.52', '$63.52');
insert into books (author, title, price_old, price) values ('Martie Troy', 'orci mauris lacinia', '$146.52', '$61.22');
insert into books (author, title, price_old, price) values ('Edik Chin', 'nulla elit ac nulla sed', '$158.22', '$61.22');
insert into books (author, title, price_old, price) values ('Dilly Broggini', 'morbi vestibulum velit id', '$184.52', '$13.42');
insert into books (author, title, price_old, price) values ('Natalee Manis', 'lorem quisque ut erat', '$113.42', '$87.82');
insert into books (author, title, price_old, price) values ('Anthiathia Leebetter', 'porttitor id consequat', '$169.62', '$15.62');
insert into books (author, title, price_old, price) values ('Luigi Gilbank', 'pede ullamcorper augue a suscipit', '$145.62', '$22.72');
insert into books (author, title, price_old, price) values ('Ivett Moatt', 'fusce lacus purus aliquet at', '$101.52', '$12.12');
insert into books (author, title, price_old, price) values ('Berkley Rohan', 'sapien arcu sed augue', '$100.42', '$05.62');
insert into books (author, title, price_old, price) values ('Merline Longshaw', 'non mauris morbi', '$198.22', '$51.52');
insert into books (author, title, price_old, price) values ('Olia Adnett', 'cubilia curae nulla dapibus', '$180.12', '$61.52');
insert into books (author, title, price_old, price) values ('Kahlil Srawley', 'ipsum dolor sit amet', '$158.32', '$47.52');
insert into books (author, title, price_old, price) values ('Carlotta Wordsley', 'id massa', '$173.32', '$93.32');
insert into books (author, title, price_old, price) values ('Madalyn Picford', 'volutpat dui maecenas tristique', '$191.62', '$11.72');
insert into books (author, title, price_old, price) values ('Conrado Tibb', 'nulla ac enim', '$101.62', '$72.42');
insert into books (author, title, price_old, price) values ('Rivkah Flaverty', 'risus auctor', '$143.42', '$97.82');
insert into books (author, title, price_old, price) values ('Erin Hakking', 'a pede', '$131.82', '$45.92');
insert into books (author, title, price_old, price) values ('Sascha Stanyforth', 'rhoncus aliquet pulvinar sed nisl', '$157.52', '$48.72');
insert into books (author, title, price_old, price) values ('Dorie Jannings', 'odio elementum eu', '$197.52', '$54.72');
insert into books (author, title, price_old, price) values ('Janessa Batt', 'est risus', '$166.12', '$51.72');
insert into books (author, title, price_old, price) values ('Charlean Flooks', 'volutpat quam pede lobortis', '$148.92', '$80.22');
insert into books (author, title, price_old, price) values ('Giuseppe Chappel', 'nam ultrices', '$116.32', '$24.22');
insert into books (author, title, price_old, price) values ('Pooh Verrechia', 'dui proin leo odio porttitor', '$117.92', '$82.62');
insert into books (author, title, price_old, price) values ('Hillie Inston', 'suspendisse potenti nullam porttitor', '$131.02', '$99.32');
insert into books (author, title, price_old, price) values ('Van Izhakov', 'pellentesque volutpat dui maecenas tristique', '$118.52', '$45.82');
insert into books (author, title, price_old, price) values ('Micky Sondon', 'ultrices vel', '$128.72', '$57.52');
insert into books (author, title, price_old, price) values ('Geneva Blundell', 'nec sem', '$163.82', '$08.62');
insert into books (author, title, price_old, price) values ('Shane Clynmans', 'enim blandit mi in porttitor', '$138.32', '$19.22');
insert into books (author, title, price_old, price) values ('Emmye Hartman', 'ipsum aliquam non mauris', '$186.32', '$46.42');
insert into books (author, title, price_old, price) values ('Jarrod MacBean', 'sit amet cursus id turpis', '$104.32', '$58.52');
insert into books (author, title, price_old, price) values ('Livvy Gerran', 'ridiculus mus etiam', '$107.02', '$29.32');
insert into books (author, title, price_old, price) values ('Berkley Jenkison', 'quisque arcu libero rutrum', '$124.12', '$81.02');
insert into books (author, title, price_old, price) values ('Yetta Carbert', 'integer ac leo pellentesque', '$164.42', '$01.32');
insert into books (author, title, price_old, price) values ('Laurent Readwing', 'turpis sed ante vivamus', '$129.12', '$28.82');
insert into books (author, title, price_old, price) values ('Juana Elcox', 'nunc vestibulum', '$166.62', '$49.22');
insert into books (author, title, price_old, price) values ('Bron Walles', 'neque duis', '$104.72', '$62.12');
insert into books (author, title, price_old, price) values ('Keelby Stolberger', 'pellentesque eget', '$186.12', '$35.82');
insert into books (author, title, price_old, price) values ('Gaylor O''Canavan', 'diam neque', '$190.32', '$90.82');
insert into books (author, title, price_old, price) values ('Theresina Boase', 'aliquam augue', '$188.72', '$70.92');
insert into books (author, title, price_old, price) values ('Lynea Grayling', 'rhoncus aliquet pulvinar sed', '$124.12', '$57.92');
insert into books (author, title, price_old, price) values ('Wylie McMeeking', 'blandit lacinia erat vestibulum', '$159.42', '$48.02');
insert into books (author, title, price_old, price) values ('Taryn Burchett', 'sit amet erat nulla tempus', '$126.52', '$64.32');
insert into books (author, title, price_old, price) values ('Jo-anne Scogin', 'ut volutpat', '$141.02', '$41.82');
insert into books (author, title, price_old, price) values ('Lynna Gierek', 'fusce posuere felis sed lacus', '$130.02', '$12.52');
insert into books (author, title, price_old, price) values ('Andros Donavan', 'orci luctus et ultrices posuere', '$194.12', '$54.82');
insert into books (author, title, price_old, price) values ('Vincent Adamides', 'pharetra magna ac consequat metus', '$134.82', '$15.72');
insert into books (author, title, price_old, price) values ('Nadya Aldren', 'dolor vel est donec odio', '$199.32', '$36.22');
insert into books (author, title, price_old, price) values ('Barnie Armsden', 'vestibulum vestibulum ante ipsum primis', '$175.72', '$49.82');
insert into books (author, title, price_old, price) values ('Sammie Barbrick', 'pellentesque eget', '$156.22', '$02.72');
insert into books (author, title, price_old, price) values ('Lucila Renzo', 'vel pede', '$198.62', '$71.92');
insert into books (author, title, price_old, price) values ('Lena Shuttell', 'orci luctus et', '$180.82', '$18.32');
insert into books (author, title, price_old, price) values ('Gery Belamy', 'primis in faucibus orci', '$115.12', '$21.32');
insert into books (author, title, price_old, price) values ('Nickie Ibbitson', 'id ligula suspendisse ornare', '$197.52', '$08.92');
insert into books (author, title, price_old, price) values ('Melamie Allen', 'nulla sed', '$104.72', '$63.32');
insert into books (author, title, price_old, price) values ('Inesita Larenson', 'in libero ut massa', '$177.82', '$63.82');
insert into books (author, title, price_old, price) values ('Rick Harvey', 'nisi venenatis tristique', '$127.02', '$15.72');
insert into books (author, title, price_old, price) values ('Hubey Joney', 'eu est congue elementum in', '$135.02', '$38.02');
insert into books (author, title, price_old, price) values ('Lyndy Chese', 'elit ac nulla sed vel', '$120.42', '$28.22');
insert into books (author, title, price_old, price) values ('Nealson Ream', 'placerat praesent', '$124.32', '$96.42');
insert into books (author, title, price_old, price) values ('Marlee Houldcroft', 'sollicitudin vitae consectetuer eget', '$134.72', '$21.22');
insert into books (author, title, price_old, price) values ('Kathy Tebboth', 'at nulla suspendisse', '$185.22', '$71.42');
insert into books (author, title, price_old, price) values ('Fair Jasiak', 'faucibus cursus', '$139.52', '$99.12');
insert into books (author, title, price_old, price) values ('Edeline Nowaczyk', 'odio donec vitae nisi nam', '$182.52', '$39.32');
insert into books (author, title, price_old, price) values ('Barney Blankhorn', 'semper porta volutpat', '$156.72', '$77.92');
insert into books (author, title, price_old, price) values ('Vilhelmina Moraleda', 'aenean fermentum', '$118.52', '$01.32');
insert into books (author, title, price_old, price) values ('Giordano Urquhart', 'porttitor lacus at', '$119.02', '$48.12');
insert into books (author, title, price_old, price) values ('Harwell Lawling', 'ipsum primis in', '$174.82', '$84.12');
insert into books (author, title, price_old, price) values ('Stella Sandeman', 'vel ipsum praesent blandit lacinia', '$111.52', '$31.72');
insert into books (author, title, price_old, price) values ('Jo Myerscough', 'praesent id massa id nisl', '$137.52', '$85.12');
insert into books (author, title, price_old, price) values ('Rivy Allardyce', 'habitasse platea dictumst', '$150.52', '$28.12');
insert into books (author, title, price_old, price) values ('Hyacintha Attenburrow', 'imperdiet nullam orci pede venenatis', '$165.02', '$33.22');
insert into books (author, title, price_old, price) values ('Baron Skillanders', 'ut erat', '$178.52', '$53.52');
insert into books (author, title, price_old, price) values ('Elston Thicking', 'nisi nam ultrices libero', '$105.82', '$65.82');
insert into books (author, title, price_old, price) values ('Laetitia Fitzhenry', 'integer ac leo pellentesque', '$169.22', '$87.72');
insert into books (author, title, price_old, price) values ('Ruperta Praundl', 'nulla nisl nunc nisl duis', '$121.52', '$44.42');
insert into books (author, title, price_old, price) values ('Annabelle Kollatsch', 'dui vel sem', '$156.92', '$16.12');
insert into books (author, title, price_old, price) values ('Bennie Hastler', 'convallis nunc proin at turpis', '$108.52', '$36.52');
insert into books (author, title, price_old, price) values ('Mallory Farran', 'ut massa', '$124.52', '$60.32');
insert into books (author, title, price_old, price) values ('Hagan Pirolini', 'sed tristique in tempus', '$104.92', '$45.02');
insert into books (author, title, price_old, price) values ('Cornie McKeaney', 'fusce consequat nulla', '$170.82', '$75.92');
insert into books (author, title, price_old, price) values ('Scot Lammerich', 'turpis nec euismod scelerisque quam', '$184.72', '$20.62');
insert into books (author, title, price_old, price) values ('Sib Binton', 'interdum mauris non ligula', '$152.82', '$05.42');
insert into books (author, title, price_old, price) values ('Loni Jennrich', 'vel nulla eget eros', '$131.62', '$96.92');
insert into books (author, title, price_old, price) values ('Willette Shedd', 'sollicitudin vitae consectetuer eget', '$184.72', '$55.92');
insert into books (author, title, price_old, price) values ('Kennie Chate', 'duis bibendum', '$137.82', '$40.22');
insert into books (author, title, price_old, price) values ('Jaclyn Iron', 'in hac habitasse platea dictumst', '$172.02', '$47.02');
insert into books (author, title, price_old, price) values ('Alex Bellard', 'nunc vestibulum ante ipsum primis', '$137.02', '$57.12');
insert into books (author, title, price_old, price) values ('Regina Owbrick', 'cubilia curae donec pharetra magna', '$148.52', '$45.22');
insert into books (author, title, price_old, price) values ('Wilma Diviney', 'nisi vulputate nonummy maecenas tincidunt', '$180.62', '$99.62');
insert into books (author, title, price_old, price) values ('Ardys Graysmark', 'dolor quis odio consequat', '$192.62', '$30.82');
insert into books (author, title, price_old, price) values ('Jessalin Heningam', 'porttitor pede justo', '$167.22', '$44.32');
insert into books (author, title, price_old, price) values ('Ranique Witherup', 'libero convallis eget', '$116.42', '$22.52');
insert into books (author, title, price_old, price) values ('Elvira Santora', 'curae donec pharetra magna', '$107.62', '$18.52');
insert into books (author, title, price_old, price) values ('Babbette Jeavon', 'praesent blandit', '$177.52', '$29.22');
insert into books (author, title, price_old, price) values ('Arlyn Trevance', 'mauris sit amet', '$117.42', '$53.22');
insert into books (author, title, price_old, price) values ('Norton Shirley', 'augue vel accumsan tellus nisi', '$144.72', '$16.22');
insert into books (author, title, price_old, price) values ('Leigh Lavery', 'morbi odio odio', '$159.02', '$74.82');
insert into books (author, title, price_old, price) values ('Lyda Gladbach', 'mus etiam', '$173.92', '$95.92');
insert into books (author, title, price_old, price) values ('Davina Dougher', 'curabitur at ipsum ac', '$105.42', '$31.02');
insert into books (author, title, price_old, price) values ('Kelila Gergus', 'pellentesque volutpat', '$149.22', '$02.72');
insert into books (author, title, price_old, price) values ('Elsey Bridgens', 'dignissim vestibulum vestibulum ante', '$131.52', '$54.62');
insert into books (author, title, price_old, price) values ('Petunia Pesak', 'pede venenatis non sodales sed', '$182.62', '$11.52');
insert into books (author, title, price_old, price) values ('Brandy Stigers', 'ullamcorper purus sit amet', '$156.12', '$58.22');
insert into books (author, title, price_old, price) values ('Theodor Haines', 'volutpat in', '$139.92', '$03.42');
insert into books (author, title, price_old, price) values ('Clementine Parkey', 'ipsum praesent blandit lacinia', '$116.82', '$83.22');
insert into books (author, title, price_old, price) values ('Gannon Giottoi', 'vulputate elementum nullam', '$110.12', '$32.02');
insert into books (author, title, price_old, price) values ('Rikki Rollinson', 'sit amet nulla', '$134.82', '$83.92');
insert into books (author, title, price_old, price) values ('Homere Klemencic', 'varius ut blandit non interdum', '$167.92', '$65.92');
insert into books (author, title, price_old, price) values ('Romy Mathevet', 'morbi porttitor', '$191.72', '$00.92');
insert into books (author, title, price_old, price) values ('Milty Thyer', 'consequat lectus in est risus', '$134.72', '$81.72');
insert into books (author, title, price_old, price) values ('Nani Martinez', 'montes nascetur', '$185.32', '$81.32');
insert into books (author, title, price_old, price) values ('Noreen Adami', 'tristique in tempus', '$199.42', '$80.62');
insert into books (author, title, price_old, price) values ('Zulema Korf', 'duis aliquam', '$173.92', '$15.52');
insert into books (author, title, price_old, price) values ('Angelique Simpson', 'in ante vestibulum ante ipsum', '$185.12', '$39.32');
insert into books (author, title, price_old, price) values ('Kalindi Mc Trusty', 'maecenas pulvinar lobortis', '$175.02', '$20.92');
insert into books (author, title, price_old, price) values ('Nicolette Annes', 'aliquam quis turpis eget', '$134.82', '$51.32');
insert into books (author, title, price_old, price) values ('Stavro Monkleigh', 'luctus nec', '$108.92', '$00.42');
insert into books (author, title, price_old, price) values ('Susannah Borkett', 'nulla tempus', '$171.22', '$60.92');
insert into books (author, title, price_old, price) values ('Jennica Ruprechter', 'semper sapien a', '$117.22', '$81.92');
insert into books (author, title, price_old, price) values ('Peadar Clague', 'dolor sit', '$199.82', '$18.92');
insert into books (author, title, price_old, price) values ('Nefen Kittiman', 'est risus auctor sed tristique', '$172.22', '$42.42');
insert into books (author, title, price_old, price) values ('Lynette Cantle', 'hac habitasse platea dictumst maecenas', '$198.62', '$58.12');
insert into books (author, title, price_old, price) values ('Joey Wolpert', 'in felis eu sapien cursus', '$162.72', '$09.12');
insert into books (author, title, price_old, price) values ('Sharona Eisikowitz', 'aliquet at', '$107.22', '$61.62');
insert into books (author, title, price_old, price) values ('Ignacius McGarvie', 'eu sapien cursus vestibulum', '$150.82', '$27.92');
insert into books (author, title, price_old, price) values ('Westbrook Twopenny', 'sodales sed', '$164.92', '$49.22');
insert into books (author, title, price_old, price) values ('Mari Howieson', 'non quam', '$171.52', '$29.72');
insert into books (author, title, price_old, price) values ('Karylin Egre', 'ante vestibulum ante ipsum', '$185.32', '$37.42');
insert into books (author, title, price_old, price) values ('Abby Garland', 'dictumst maecenas ut', '$144.22', '$85.72');
insert into books (author, title, price_old, price) values ('Nomi Hanscome', 'vestibulum velit', '$186.52', '$89.52');
insert into books (author, title, price_old, price) values ('Bee Terbrugge', 'vel augue vestibulum ante ipsum', '$174.52', '$44.22');
insert into books (author, title, price_old, price) values ('Leonard Stapels', 'eleifend quam a', '$115.22', '$60.72');
insert into books (author, title, price_old, price) values ('Noelyn Saben', 'curabitur at ipsum ac tellus', '$197.52', '$46.42');
insert into books (author, title, price_old, price) values ('Constanta Blackmore', 'ut volutpat sapien', '$155.52', '$47.32');
insert into books (author, title, price_old, price) values ('Dwain Allans', 'porta volutpat', '$140.92', '$86.52');
insert into books (author, title, price_old, price) values ('Sandye Bohin', 'nec dui luctus', '$108.72', '$53.92');
insert into books (author, title, price_old, price) values ('Rubin Hainge', 'mi sit', '$159.02', '$25.92');
insert into books (author, title, price_old, price) values ('Kile Francescozzi', 'nulla ac enim in', '$155.42', '$04.72');
insert into books (author, title, price_old, price) values ('Ddene Wellwood', 'nullam varius nulla facilisi', '$161.72', '$53.52');
insert into books (author, title, price_old, price) values ('Ingrim Lynnett', 'luctus et ultrices posuere', '$127.62', '$65.82');
insert into books (author, title, price_old, price) values ('Trista Blum', 'condimentum id luctus nec', '$186.52', '$09.22');
insert into books (author, title, price_old, price) values ('Artie Nussen', 'orci mauris lacinia sapien quis', '$112.02', '$78.32');
insert into books (author, title, price_old, price) values ('Yolanthe Allaway', 'vestibulum ante ipsum', '$188.02', '$47.32');
insert into books (author, title, price_old, price) values ('Lazarus Mansbridge', 'nulla neque libero', '$166.92', '$96.92');
insert into books (author, title, price_old, price) values ('Olenka Giroldo', 'dui maecenas tristique est et', '$128.52', '$82.92');
insert into books (author, title, price_old, price) values ('Glad Maven', 'curabitur gravida nisi at nibh', '$123.22', '$16.82');
insert into books (author, title, price_old, price) values ('Ashley Sprosson', 'a nibh in quis justo', '$171.12', '$25.62');
insert into books (author, title, price_old, price) values ('Bale Charrette', 'dictumst morbi vestibulum velit id', '$174.32', '$48.22');
insert into books (author, title, price_old, price) values ('Gorden Kassidy', 'ipsum integer a', '$102.82', '$56.52');
insert into books (author, title, price_old, price) values ('Prudi Ternouth', 'posuere metus vitae', '$103.62', '$28.72');
insert into books (author, title, price_old, price) values ('Eachelle Shambroke', 'sodales sed tincidunt eu felis', '$164.42', '$05.02');
insert into books (author, title, price_old, price) values ('Natty Midlane', 'turpis sed', '$184.42', '$78.72');
insert into books (author, title, price_old, price) values ('Conrad Leftley', 'posuere felis sed', '$144.52', '$39.82');
insert into books (author, title, price_old, price) values ('Rae Padillo', 'eget nunc donec quis orci', '$144.12', '$32.72');
insert into books (author, title, price_old, price) values ('Lucienne Stearns', 'vel pede morbi', '$153.32', '$78.42');
insert into books (author, title, price_old, price) values ('Lewie Hebbron', 'nisl venenatis lacinia aenean sit', '$184.32', '$63.42');
insert into books (author, title, price_old, price) values ('Julianne Licquorish', 'sapien urna pretium', '$175.92', '$63.32');
insert into books (author, title, price_old, price) values ('Aldridge Gaddas', 'ipsum primis', '$154.12', '$38.82');
insert into books (author, title, price_old, price) values ('Pier Loade', 'nec euismod scelerisque quam', '$198.72', '$61.92');
insert into books (author, title, price_old, price) values ('Allegra Gresser', 'metus arcu adipiscing', '$132.02', '$81.62');
insert into books (author, title, price_old, price) values ('Elsie Binyon', 'posuere nonummy integer', '$129.92', '$50.12');
insert into books (author, title, price_old, price) values ('Richard Bifield', 'ipsum integer a', '$137.32', '$43.92');
insert into books (author, title, price_old, price) values ('Natalina Henkens', 'libero ut', '$196.82', '$56.82');
insert into books (author, title, price_old, price) values ('Edythe Aprahamian', 'ultrices posuere cubilia', '$185.82', '$24.32');
insert into books (author, title, price_old, price) values ('Berti Barenski', 'pellentesque quisque porta', '$130.62', '$53.32');
insert into books (author, title, price_old, price) values ('Tarrah Wherrit', 'neque aenean auctor gravida sem', '$149.82', '$87.42');
insert into books (author, title, price_old, price) values ('Dare Linden', 'et ultrices', '$150.32', '$40.92');
insert into books (author, title, price_old, price) values ('Cort Herety', 'diam in magna bibendum imperdiet', '$136.12', '$54.32');
insert into books (author, title, price_old, price) values ('Chery Arkell', 'etiam vel augue vestibulum rutrum', '$109.42', '$92.92');
insert into books (author, title, price_old, price) values ('Emylee Hartopp', 'nulla quisque arcu', '$138.92', '$50.82');
insert into books (author, title, price_old, price) values ('Essie Corcut', 'primis in faucibus orci luctus', '$190.02', '$90.52');
insert into books (author, title, price_old, price) values ('Sorcha Rawood', 'convallis duis consequat', '$178.62', '$12.42');
insert into books (author, title, price_old, price) values ('Agnesse Douce', 'elementum in hac habitasse platea', '$128.72', '$22.12');
insert into books (author, title, price_old, price) values ('Tressa Gierok', 'ante ipsum primis in', '$166.32', '$89.62');
insert into books (author, title, price_old, price) values ('Mindy Gillions', 'vel nulla eget eros', '$112.32', '$77.02');
insert into books (author, title, price_old, price) values ('Rand Routh', 'nulla nisl nunc nisl duis', '$114.42', '$09.92');
insert into books (author, title, price_old, price) values ('Vikky Zuann', 'congue diam id ornare', '$117.42', '$83.02');
insert into books (author, title, price_old, price) values ('Tommy Janovsky', 'orci pede venenatis non', '$146.22', '$92.12');
insert into books (author, title, price_old, price) values ('Emmye Dover', 'ullamcorper augue', '$164.82', '$01.12');
insert into books (author, title, price_old, price) values ('Joana Wybern', 'urna pretium nisl', '$182.62', '$36.92');
insert into books (author, title, price_old, price) values ('Modestia Haville', 'semper est quam', '$127.42', '$43.92');
insert into books (author, title, price_old, price) values ('Olivia Lee', 'diam erat fermentum', '$108.02', '$11.22');
insert into books (author, title, price_old, price) values ('Kathy Troth', 'blandit lacinia erat', '$174.82', '$64.92');
insert into books (author, title, price_old, price) values ('Grazia Berrow', 'tellus nisi eu orci mauris', '$164.42', '$90.32');
insert into books (author, title, price_old, price) values ('Nicolina Streight', 'nulla tellus', '$178.82', '$25.72');
insert into books (author, title, price_old, price) values ('Gabi Wrenn', 'eros elementum pellentesque quisque', '$155.52', '$91.12');
insert into books (author, title, price_old, price) values ('Cass Armsby', 'ut odio cras mi', '$197.82', '$54.62');
insert into books (author, title, price_old, price) values ('Herrick Tomasoni', 'turpis sed ante', '$113.52', '$29.22');
insert into books (author, title, price_old, price) values ('Sibel Floyde', 'duis aliquam convallis nunc proin', '$123.02', '$26.42');
insert into books (author, title, price_old, price) values ('Mill Stanborough', 'egestas metus aenean fermentum', '$148.22', '$84.52');
insert into books (author, title, price_old, price) values ('Olivette Winsbury', 'nulla dapibus', '$192.82', '$48.72');
insert into books (author, title, price_old, price) values ('Wilmar Huggons', 'eu felis fusce posuere', '$127.92', '$99.32');
insert into books (author, title, price_old, price) values ('Mirabel Bloomfield', 'at lorem integer tincidunt ante', '$129.22', '$57.52');
insert into books (author, title, price_old, price) values ('Rafe Paice', 'ipsum primis in faucibus', '$130.42', '$62.52');
insert into books (author, title, price_old, price) values ('Daryn Klimashevich', 'dui vel', '$112.82', '$41.12');
insert into books (author, title, price_old, price) values ('Klarika Ausher', 'aliquam augue quam sollicitudin vitae', '$122.62', '$97.32');
insert into books (author, title, price_old, price) values ('Sigismond Borge', 'nibh ligula nec sem duis', '$155.52', '$60.62');
insert into books (author, title, price_old, price) values ('Crysta Brumby', 'dolor morbi vel lectus in', '$125.52', '$18.52');
insert into books (author, title, price_old, price) values ('Blancha Hourihane', 'eget semper rutrum nulla nunc', '$164.92', '$94.02');
insert into books (author, title, price_old, price) values ('Duke Izon', 'blandit non interdum', '$153.12', '$05.42');
insert into books (author, title, price_old, price) values ('Lilla Arnely', 'amet diam in magna bibendum', '$168.52', '$00.12');
insert into books (author, title, price_old, price) values ('Justino Litton', 'tempus sit amet sem fusce', '$198.02', '$30.32');
insert into books (author, title, price_old, price) values ('Ricky Sherrin', 'congue eget', '$100.62', '$98.42');
insert into books (author, title, price_old, price) values ('Giorgia Doggart', 'eros elementum pellentesque quisque', '$135.22', '$49.72');
insert into books (author, title, price_old, price) values ('Vanni Luetchford', 'turpis a pede', '$169.42', '$73.92');
insert into books (author, title, price_old, price) values ('Sonnie Garken', 'justo eu massa donec dapibus', '$110.02', '$78.12');
insert into books (author, title, price_old, price) values ('Deeanne Spalton', 'posuere nonummy integer non velit', '$115.02', '$02.22');
insert into books (author, title, price_old, price) values ('Sandor Tarpey', 'proin leo odio porttitor', '$190.22', '$85.72');
insert into books (author, title, price_old, price) values ('Quintus Vignal', 'maecenas ut massa quis augue', '$188.92', '$12.62');
insert into books (author, title, price_old, price) values ('Jard Wilshin', 'sapien iaculis congue vivamus metus', '$107.02', '$12.92');
insert into books (author, title, price_old, price) values ('Junina Readshall', 'erat id mauris vulputate', '$181.32', '$83.52');
insert into books (author, title, price_old, price) values ('Portia Binden', 'accumsan tellus nisi eu orci', '$102.72', '$54.92');
insert into books (author, title, price_old, price) values ('Joelie Poulett', 'libero quis', '$121.92', '$78.72');
insert into books (author, title, price_old, price) values ('Maren Peres', 'donec diam neque', '$126.92', '$88.42');
insert into books (author, title, price_old, price) values ('Roley Place', 'accumsan odio curabitur convallis duis', '$150.32', '$00.32');
insert into books (author, title, price_old, price) values ('Linnie Robertsen', 'dictumst morbi vestibulum velit', '$104.82', '$68.92');
insert into books (author, title, price_old, price) values ('Nata Syne', 'lacus at velit vivamus vel', '$102.52', '$94.92');
insert into books (author, title, price_old, price) values ('Gloriana Ends', 'augue quam', '$115.22', '$41.52');
insert into books (author, title, price_old, price) values ('Kelcie Frowd', 'orci luctus', '$121.92', '$90.12');
insert into books (author, title, price_old, price) values ('Brittan Konig', 'pellentesque ultrices mattis odio donec', '$147.72', '$08.32');
insert into books (author, title, price_old, price) values ('Alie Brecknock', 'augue aliquam erat volutpat in', '$160.52', '$76.72');
insert into books (author, title, price_old, price) values ('Grissel Rawne', 'morbi odio odio', '$115.12', '$56.62');
insert into books (author, title, price_old, price) values ('Veriee Pendlebery', 'donec dapibus duis at velit', '$126.52', '$01.62');
insert into books (author, title, price_old, price) values ('Sergent Khrishtafovich', 'at velit eu', '$111.82', '$71.82');
insert into books (author, title, price_old, price) values ('Jacquette Hemphall', 'fermentum donec ut', '$161.32', '$81.22');
insert into books (author, title, price_old, price) values ('Pail Antram', 'in tempor turpis nec euismod', '$175.82', '$96.72');
insert into books (author, title, price_old, price) values ('Harriet Grimmer', 'semper interdum', '$135.12', '$25.22');
insert into books (author, title, price_old, price) values ('Sonny Hosten', 'erat volutpat', '$105.02', '$67.92');
insert into books (author, title, price_old, price) values ('Panchito Scardifeild', 'quam nec dui luctus', '$145.62', '$28.82');
insert into books (author, title, price_old, price) values ('Colly Jeram', 'purus phasellus in felis donec', '$101.42', '$81.52');
insert into books (author, title, price_old, price) values ('Steffi Oggers', 'ipsum ac tellus semper interdum', '$152.62', '$98.82');
insert into books (author, title, price_old, price) values ('Steffen Crewe', 'maecenas leo odio condimentum id', '$185.02', '$14.02');
insert into books (author, title, price_old, price) values ('Helen Anselmi', 'accumsan odio curabitur', '$118.52', '$95.42');
insert into books (author, title, price_old, price) values ('Westbrook Danielsky', 'aenean auctor gravida sem', '$198.12', '$92.72');
insert into books (author, title, price_old, price) values ('Niki Maddy', 'nulla dapibus dolor vel', '$198.82', '$00.22');
insert into books (author, title, price_old, price) values ('Taryn McGeouch', 'rhoncus aliquet', '$188.62', '$83.72');
insert into books (author, title, price_old, price) values ('Keith Wigfall', 'sit amet eros', '$124.82', '$43.82');
insert into books (author, title, price_old, price) values ('Farleigh Keam', 'lectus suspendisse potenti', '$145.12', '$39.82');
insert into books (author, title, price_old, price) values ('Mame Clarkson', 'duis ac nibh fusce lacus', '$157.72', '$67.52');
insert into books (author, title, price_old, price) values ('Gonzalo Wones', 'phasellus in felis donec semper', '$159.52', '$42.82');
insert into books (author, title, price_old, price) values ('Ebeneser Huffy', 'neque sapien placerat ante', '$127.92', '$49.52');
insert into books (author, title, price_old, price) values ('Miguelita Claessens', 'in purus eu', '$103.02', '$64.52');
insert into books (author, title, price_old, price) values ('Dayna Antram', 'vivamus in felis eu sapien', '$132.52', '$27.12');
insert into books (author, title, price_old, price) values ('Sim Drance', 'sit amet lobortis sapien sapien', '$188.72', '$37.72');
insert into books (author, title, price_old, price) values ('Flora Killik', 'amet sem fusce', '$152.02', '$73.92');
insert into books (author, title, price_old, price) values ('Dorena Hardwidge', 'sit amet nulla', '$104.72', '$19.12');
insert into books (author, title, price_old, price) values ('Flossie Ingon', 'eget orci vehicula condimentum', '$119.42', '$56.52');
insert into books (author, title, price_old, price) values ('Woodrow Alfwy', 'faucibus cursus urna', '$104.72', '$44.22');
insert into books (author, title, price_old, price) values ('Timothy Dunham', 'sapien non mi integer ac', '$131.92', '$22.32');
insert into books (author, title, price_old, price) values ('Tony Pouton', 'vulputate justo in blandit ultrices', '$142.52', '$84.62');
insert into books (author, title, price_old, price) values ('Wheeler Scroggins', 'viverra eget congue', '$196.72', '$54.92');
insert into books (author, title, price_old, price) values ('Peterus Sherer', 'ultrices mattis odio donec', '$196.42', '$37.02');
insert into books (author, title, price_old, price) values ('Lisha Stoop', 'tempus vel', '$190.22', '$76.52');
insert into books (author, title, price_old, price) values ('Holt Hark', 'congue diam id ornare imperdiet', '$116.22', '$84.52');
insert into books (author, title, price_old, price) values ('Katey Leipnik', 'massa id nisl', '$193.82', '$90.82');
insert into books (author, title, price_old, price) values ('Deana Golding', 'quis orci nullam', '$165.02', '$03.12');
insert into books (author, title, price_old, price) values ('Alberta Gatman', 'faucibus orci', '$186.32', '$75.22');
insert into books (author, title, price_old, price) values ('Blanch Churchman', 'eget eros elementum', '$155.42', '$58.92');
insert into books (author, title, price_old, price) values ('Kean Haste', 'placerat praesent blandit nam', '$150.52', '$90.72');
insert into books (author, title, price_old, price) values ('Rowland Stiegar', 'leo maecenas pulvinar lobortis', '$193.12', '$10.12');
insert into books (author, title, price_old, price) values ('Mathilde Grzesiak', 'quis turpis eget elit sodales', '$190.72', '$00.22');
insert into books (author, title, price_old, price) values ('Lelah Mosey', 'lacus morbi quis tortor id', '$173.82', '$50.22');
insert into books (author, title, price_old, price) values ('Mano Garrettson', 'placerat ante', '$165.62', '$18.22');
insert into books (author, title, price_old, price) values ('Gilberte Adamiec', 'vel sem sed', '$199.72', '$97.82');
insert into books (author, title, price_old, price) values ('Golda Memmory', 'hac habitasse platea', '$181.22', '$98.12');
insert into books (author, title, price_old, price) values ('Verge Ellum', 'lacus at velit vivamus', '$124.32', '$69.82');
insert into books (author, title, price_old, price) values ('Raffarty Selburn', 'ac leo', '$177.02', '$32.92');
insert into books (author, title, price_old, price) values ('Gustave Vondrys', 'elementum in hac habitasse', '$109.62', '$10.62');
insert into books (author, title, price_old, price) values ('Rowan Ghilks', 'sapien quis libero nullam sit', '$162.02', '$51.92');
insert into books (author, title, price_old, price) values ('Gregoor Evesque', 'sed interdum venenatis turpis enim', '$179.32', '$21.32');
insert into books (author, title, price_old, price) values ('Mariya Huzzey', 'morbi vestibulum', '$160.92', '$26.92');
insert into books (author, title, price_old, price) values ('Romonda Lloyd-Williams', 'justo lacinia eget', '$173.12', '$04.72');
insert into books (author, title, price_old, price) values ('Joanna Rean', 'auctor gravida', '$147.02', '$74.12');
insert into books (author, title, price_old, price) values ('Odetta Naismith', 'venenatis turpis enim blandit mi', '$168.02', '$85.52');
insert into books (author, title, price_old, price) values ('Hart Nutt', 'parturient montes', '$158.22', '$88.62');
insert into books (author, title, price_old, price) values ('Rubie Loren', 'cubilia curae donec pharetra magna', '$110.42', '$87.02');
insert into books (author, title, price_old, price) values ('Erich Fathers', 'elementum in hac habitasse platea', '$146.12', '$52.82');
insert into books (author, title, price_old, price) values ('Zeke Maty', 'aliquet pulvinar sed', '$169.32', '$46.92');
insert into books (author, title, price_old, price) values ('Stefa Longhorn', 'lobortis ligula sit', '$181.82', '$34.72');
insert into books (author, title, price_old, price) values ('Cele Casbon', 'rhoncus sed vestibulum sit', '$111.92', '$30.22');
insert into books (author, title, price_old, price) values ('Jena Tuiller', 'sodales scelerisque mauris sit amet', '$169.22', '$92.32');
insert into books (author, title, price_old, price) values ('Maurise Lythgoe', 'orci eget orci', '$140.42', '$20.72');
insert into books (author, title, price_old, price) values ('Biron Benardet', 'rutrum nulla', '$131.82', '$33.42');
insert into books (author, title, price_old, price) values ('Ozzy Lupson', 'donec ut dolor morbi vel', '$139.12', '$43.92');
insert into books (author, title, price_old, price) values ('Julee Maytum', 'viverra diam vitae', '$177.52', '$02.82');
insert into books (author, title, price_old, price) values ('Cyndie Dirkin', 'lacus at velit vivamus vel', '$151.32', '$04.52');
insert into books (author, title, price_old, price) values ('Megen Hofer', 'sed sagittis nam congue', '$135.62', '$88.12');
insert into books (author, title, price_old, price) values ('Curtice Plummer', 'vestibulum sit', '$183.52', '$03.22');
insert into books (author, title, price_old, price) values ('Ronnica Driscoll', 'blandit mi in porttitor pede', '$141.02', '$27.02');
insert into books (author, title, price_old, price) values ('Waly Opfer', 'augue a suscipit', '$194.52', '$63.12');
insert into books (author, title, price_old, price) values ('Shelia Quoit', 'lectus aliquam sit amet diam', '$175.82', '$92.82');
insert into books (author, title, price_old, price) values ('Shanan Yarwood', 'leo odio condimentum id luctus', '$106.62', '$69.32');
insert into books (author, title, price_old, price) values ('Enrichetta Kennet', 'tellus nisi eu orci', '$175.62', '$59.72');
insert into books (author, title, price_old, price) values ('Benedetto Balsdone', 'neque libero', '$176.42', '$38.12');
insert into books (author, title, price_old, price) values ('Erin Lattimer', 'neque vestibulum eget vulputate', '$170.92', '$98.72');
insert into books (author, title, price_old, price) values ('Bengt Alflat', 'ultrices libero non', '$144.32', '$87.62');
insert into books (author, title, price_old, price) values ('Jermain Pendrick', 'ipsum integer a', '$134.52', '$61.32');
insert into books (author, title, price_old, price) values ('Stanfield Beartup', 'id sapien in sapien iaculis', '$141.22', '$07.52');
insert into books (author, title, price_old, price) values ('Dasi Dubois', 'rhoncus sed vestibulum sit', '$156.62', '$95.82');
insert into books (author, title, price_old, price) values ('Jarvis Bannester', 'turpis nec euismod', '$122.92', '$21.32');
insert into books (author, title, price_old, price) values ('Lydon Etheredge', 'adipiscing lorem vitae mattis', '$163.92', '$94.42');
insert into books (author, title, price_old, price) values ('Monah Davidovics', 'quisque porta volutpat erat quisque', '$106.02', '$82.92');
insert into books (author, title, price_old, price) values ('Lucia Kimbling', 'dapibus augue vel accumsan tellus', '$174.32', '$46.72');


insert into authors (author) select distinct author from books;
